package paquete;

import controles.LimpiarComponentes;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class FormularioPrincipal extends JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        this.setTitle("Principal");
        this.setLocationRelativeTo(null);
        this.setExtendedState(3);
    }

    public void limpiar() {
        LimpiarComponentes.limpiarComponentes(this.panelDatos);
    }

    public void validarEdad() {
        String expresionRegular = "[1-9]{1}([0-9]{1,2})?";
        if (this.textEdad.getText().matches(expresionRegular)) {
            JOptionPane.showMessageDialog(null, "Dato Correcto", "Infomación", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Dato Incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void validarCorreo() {
        String expresionRegular = "[a-zA-Z0-9]+[-_.]*[a-zA-Z0-9]+\\@[a-zA-Z]+\\.[a-zA-Z]+";
        if (this.textCorreo.getText().matches(expresionRegular)) {
            JOptionPane.showMessageDialog(null, "Dato Correcto", "Infomación", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Dato Incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void validarFechaNacimiento() {
        String expresionRegular = "[0-9]{2}\\-[0-9]{2}\\-[0-9]{4}";
        if (this.textFechaNacimiento.getText().matches(expresionRegular)) {
            JOptionPane.showMessageDialog(null, "Dato Correcto", "Infomación", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Dato Incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void validarTelefono() {
        String expresionRegular = "(\\+?[0-9]{2,3}\\-)?(([1-9]{1}[0-9]{5})|([1-9]{1}[0-9]{8}))";
        if (this.textTelefono.getText().matches(expresionRegular)) {
            JOptionPane.showMessageDialog(null, "Dato Correcto", "Infomación", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Dato Incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void validarPrecio() {
        String expresionRegular = "[1-9]{1}[0-9]*(\\.[0-9]{1,2})?";
        if (this.textPrecio.getText().matches(expresionRegular)) {
            JOptionPane.showMessageDialog(null, "Dato Correcto", "Infomación", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Dato Incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatos = new javax.swing.JPanel();
        labelEdad = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelFechaNacimiento = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        textEdad = new javax.swing.JTextField();
        textCorreo = new javax.swing.JTextField();
        textFechaNacimiento = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        textPrecio = new javax.swing.JTextField();
        buttonValidarEdad = new javax.swing.JButton();
        buttonValidarCorreo = new javax.swing.JButton();
        buttonValidarFechaNacimiento = new javax.swing.JButton();
        buttonValidarTelefono = new javax.swing.JButton();
        buttonValidarPrecio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelEdad.setText("Edad");

        labelCorreo.setText("Correo");

        labelFechaNacimiento.setText("Fecha de Nacimiento");

        labelTelefono.setText("Teléfono");

        labelPrecio.setText("Precio");

        buttonValidarEdad.setText("Validar");
        buttonValidarEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidarEdadActionPerformed(evt);
            }
        });

        buttonValidarCorreo.setText("Validar");
        buttonValidarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidarCorreoActionPerformed(evt);
            }
        });

        buttonValidarFechaNacimiento.setText("Validar");
        buttonValidarFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidarFechaNacimientoActionPerformed(evt);
            }
        });

        buttonValidarTelefono.setText("Validar");
        buttonValidarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidarTelefonoActionPerformed(evt);
            }
        });

        buttonValidarPrecio.setText("Validar");
        buttonValidarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidarPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEdad)
                    .addComponent(labelCorreo)
                    .addComponent(labelFechaNacimiento)
                    .addComponent(labelTelefono)
                    .addComponent(labelPrecio))
                .addGap(28, 28, 28)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textEdad)
                    .addComponent(textCorreo)
                    .addComponent(textFechaNacimiento)
                    .addComponent(textTelefono)
                    .addComponent(textPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonValidarEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonValidarCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonValidarFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonValidarTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonValidarPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdad)
                    .addComponent(textEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonValidarEdad))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCorreo)
                    .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonValidarCorreo))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaNacimiento)
                    .addComponent(textFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonValidarFechaNacimiento))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonValidarTelefono))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPrecio)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonValidarPrecio)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonValidarEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidarEdadActionPerformed
        this.validarEdad();
    }//GEN-LAST:event_buttonValidarEdadActionPerformed

    private void buttonValidarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidarCorreoActionPerformed
        this.validarCorreo();
    }//GEN-LAST:event_buttonValidarCorreoActionPerformed

    private void buttonValidarFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidarFechaNacimientoActionPerformed
        this.validarFechaNacimiento();
    }//GEN-LAST:event_buttonValidarFechaNacimientoActionPerformed

    private void buttonValidarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidarTelefonoActionPerformed
        this.validarTelefono();
    }//GEN-LAST:event_buttonValidarTelefonoActionPerformed

    private void buttonValidarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidarPrecioActionPerformed
        this.validarPrecio();
    }//GEN-LAST:event_buttonValidarPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonValidarCorreo;
    private javax.swing.JButton buttonValidarEdad;
    private javax.swing.JButton buttonValidarFechaNacimiento;
    private javax.swing.JButton buttonValidarPrecio;
    private javax.swing.JButton buttonValidarTelefono;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelFechaNacimiento;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textEdad;
    private javax.swing.JTextField textFechaNacimiento;
    private javax.swing.JTextField textPrecio;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
